@extends('layouts.app')
@section('title', 'Apply for Loan')
@section('page-title', '📝 New Loan Application')

@section('content')
<div class="los-form-container" id="losApplyForm">

    {{-- ── Step Indicator ── --}}
    <div class="step-indicator" id="stepIndicator">
        <!-- Steps will be generated by JS -->
    </div>

    <form method="POST" action="{{ route('los.store') }}" id="loanForm" enctype="multipart/form-data">
        @csrf

        {{-- ── Step 1: Customer Selection ── --}}
        <div class="panel form-step" id="step1" style="display: block;">
            <h2 class="panel-title mb-1">Select Customer</h2>
            <p class="text-muted mb-4">Choose an existing Kendra customer for the loan application</p>

            <div class="form-group">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem;">
                    <label for="customer_id" class="form-label" style="margin-bottom: 0;">Customer</label>
                    <div style="font-size: 0.875rem;">
                        <span class="text-muted">Not found? Add: </span>
                        <a href="{{ route('los.center') }}" class="btn-text" style="padding: 0; font-size: inherit;">Center</a> •
                        <a href="{{ route('los.group') }}" class="btn-text" style="padding: 0; font-size: inherit;">Group</a> •
                        <a href="{{ route('los.member') }}" class="btn-text" style="padding: 0; font-size: inherit;">Member</a>
                    </div>
                </div>
                <select id="customer_id" name="customer_id" class="form-input">
                    <option value="">-- Select a customer --</option>
                    @foreach($customers as $c)
                    <option value="{{ $c->id }}"
                        data-income="{{ $c->annual_household_income }}"
                        data-debt="{{ $c->monthly_debt_obligations }}"
                        data-name="{{ $c->full_name }}"
                        data-group="{{ $c->group->group_name ?? '' }}"
                        data-center="{{ $c->group->center->center_name ?? '' }}"
                        data-aadhaar="{{ $c->masked_aadhaar }}"
                        data-pan="{{ $c->pan_number }}"
                        {{ old('customer_id') == $c->id ? 'selected' : '' }}>
                        {{ $c->full_name }} — {{ $c->group->center->center_name ?? '' }} / {{ $c->group->group_name ?? '' }}
                    </option>
                    @endforeach
                </select>
            </div>

            {{-- Customer KYC Preview --}}
            <div id="customerPreview" class="customer-preview" style="display: none;">
                <p class="preview-title">Customer Profile</p>
                <div class="preview-grid">
                    <div><span class="preview-label">Name:</span> <span class="preview-value" id="previewName"></span></div>
                    <div><span class="preview-label">Center:</span> <span class="preview-value" id="previewCenter"></span></div>
                    <div><span class="preview-label">Group:</span> <span class="preview-value" id="previewGroup"></span></div>
                    <div><span class="preview-label">Aadhaar:</span> <span class="preview-value" id="previewAadhaar"></span></div>
                    <div><span class="preview-label">Annual Income:</span> <span class="preview-value" id="previewIncome"></span></div>
                    <div><span class="preview-label">Monthly Obligations:</span> <span class="preview-value" id="previewDebt"></span></div>
                </div>
                {{-- Income cap warning --}}
                <div id="incomeWarning" class="alert-danger mt-3" style="display: none;">
                    ⚠️ Customer annual income exceeds RBI ₹3,00,000 cap. Application will be rejected.
                </div>
            </div>
        </div>

        {{-- ── Step 2: Loan Details + FOIR Calculator ── --}}
        <div class="panel form-step" id="step2" style="display: none;">
            <h2 class="panel-title mb-1">Loan Details</h2>
            <p class="text-muted mb-4">Enter the loan parameters. The FOIR calculator updates in real-time.</p>

            <div class="form-grid">
                <div class="form-group">
                    <label class="form-label">Loan Amount (₹)</label>
                    <input type="number" id="loanAmount" name="applied_amount" min="5000" max="300000" step="1000"
                        class="form-input" value="{{ old('applied_amount', 50000) }}" required>
                </div>
                <div class="form-group">
                    <label class="form-label">Interest Rate (% p.a.)</label>
                    <input type="number" id="loanRate" name="annual_interest_rate" min="1" max="30" step="0.25"
                        class="form-input" value="{{ old('annual_interest_rate', 22) }}" required>
                </div>
                <div class="form-group">
                    <label class="form-label">Tenure (months)</label>
                    <input type="number" id="loanTenure" name="tenure" min="3" max="60"
                        class="form-input" value="{{ old('tenure', 12) }}" required>
                </div>
                <div class="form-group">
                    <label class="form-label">Repayment Frequency</label>
                    <select id="loanFrequency" name="repayment_frequency" class="form-input">
                        <option value="monthly" {{ old('repayment_frequency') == 'monthly' ? 'selected' : '' }}>Monthly</option>
                        <option value="weekly" {{ old('repayment_frequency') == 'weekly' ? 'selected' : '' }}>Weekly</option>
                    </select>
                </div>
                <div class="form-group col-span-2">
                    <label class="form-label">Loan Purpose</label>
                    <input type="text" id="loanPurpose" name="purpose" class="form-input"
                        placeholder="e.g. Dairy Business, Tailoring Unit" value="{{ old('purpose') }}">
                </div>
            </div>

            {{-- FOIR Calculator --}}
            <div class="calculator-panel">
                <p class="preview-title">📊 Real-Time FOIR Calculator</p>
                <div class="calculator-grid">
                    <div>
                        <p class="preview-label">Projected EMI</p>
                        <p class="calculator-value" id="calcEmi">₹0</p>
                    </div>
                    <div>
                        <p class="preview-label">Monthly Income</p>
                        <p class="calculator-value" id="calcIncome">₹0</p>
                    </div>
                    <div>
                        <p class="preview-label">Total Obligations</p>
                        <p class="calculator-value" id="calcObligation">₹0</p>
                    </div>
                </div>

                {{-- FOIR Gauge --}}
                <div class="gauge-container">
                    <div id="foirBar" class="gauge-bar bg-emerald">
                        <span id="foirPctText" class="gauge-text">0%</span>
                    </div>
                    <div class="gauge-marker"></div>
                    <span class="gauge-label">50% RBI Cap</span>
                </div>

                <div id="foirStatus" class="mt-3 text-sm font-medium"></div>
            </div>
        </div>

        {{-- ── Step 3: Document Upload ── --}}
        <div class="panel form-step" id="step3" style="display: none;">
            <h2 class="panel-title mb-1">KYC Documents</h2>
            <p class="text-muted mb-4">Attach customer KYC documents. Document numbers are masked for Aadhaar.</p>

            <div id="documentList" class="document-list">
                <!-- Document rows generated by JS -->
            </div>

            <button type="button" id="addDocBtn" class="btn-text mt-3">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>
                Add Another Document
            </button>
        </div>

        {{-- ── Step 4: Review & Submit ── --}}
        <div class="panel form-step" id="step4" style="display: none;">
            <h2 class="panel-title mb-1">Review & Submit</h2>
            <p class="text-muted mb-4">Verify the application details before submitting.</p>

            <div class="review-grid">
                <div class="review-box">
                    <p class="preview-title">Customer</p>
                    <p class="font-medium" id="revName"></p>
                    <p class="text-muted" id="revCenter"></p>
                </div>
                <div class="review-box">
                    <p class="preview-title">Loan</p>
                    <p class="font-medium" id="revLoan"></p>
                    <p class="text-muted" id="revEmi"></p>
                </div>
                <div class="review-box">
                    <p class="preview-title">Purpose</p>
                    <p class="font-medium" id="revPurpose"></p>
                </div>
                <div class="review-box">
                    <p class="preview-title">Documents</p>
                    <p class="font-medium" id="revDocs"></p>
                </div>
            </div>

            <div id="reviewWarning" class="alert-success mt-4">
                <p class="font-bold">✅ All RBI checks passed. Ready to submit.</p>
            </div>
        </div>

        {{-- ── Navigation Buttons ── --}}
        <div class="form-actions">
            <button type="button" id="prevBtn" class="btn-secondary" style="display: none;">← Back</button>
            <div id="spacerBtn" style="display: block;"></div>
            <button type="button" id="nextBtn" class="btn-primary" disabled>Next →</button>
            <button type="submit" id="submitBtn" class="btn-success" style="display: none;">🚀 Submit Application</button>
        </div>
    </form>
</div>

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', () => {
    // State
    let currentStep = 1;
    const totalSteps = 4;
    const steps = ['Customer', 'Loan Details', 'Documents', 'Review'];
    let docs = [{ type: 'aadhaar_card', number: '' }, { type: 'pan_card', number: '' }];
    let customerData = { income: 0, debt: 0, name: '', center: '', group: '' };

    // Elements
    const stepIndicator = document.getElementById('stepIndicator');
    const prevBtn = document.getElementById('prevBtn');
    const nextBtn = document.getElementById('nextBtn');
    const submitBtn = document.getElementById('submitBtn');
    const spacerBtn = document.getElementById('spacerBtn');
    const customerSelect = document.getElementById('customer_id');

    // Render Steps
    function renderSteps() {
        stepIndicator.innerHTML = '';
        steps.forEach((s, i) => {
            const stepNum = i + 1;
            const isActive = currentStep >= stepNum;
            const isCompleted = currentStep > stepNum;
            
            const stepDiv = document.createElement('div');
            stepDiv.className = 'step-item';
            
            const circle = document.createElement('div');
            circle.className = `step-circle ${isActive ? 'active' : ''}`;
            circle.innerText = isCompleted ? '✓' : stepNum;
            
            const label = document.createElement('span');
            label.className = `step-label ${isActive ? 'active' : ''}`;
            label.innerText = s;
            
            const wrapper = document.createElement('div');
            wrapper.className = 'step-wrapper';
            wrapper.appendChild(circle);
            wrapper.appendChild(label);
            stepDiv.appendChild(wrapper);
            
            if (i < steps.length - 1) {
                const line = document.createElement('div');
                line.className = `step-line ${isCompleted ? 'active' : ''}`;
                stepDiv.appendChild(line);
            }
            
            stepIndicator.appendChild(stepDiv);
        });
    }

    // Navigation
    function updateView() {
        for(let i=1; i<=totalSteps; i++) {
            document.getElementById(`step${i}`).style.display = (i === currentStep) ? 'block' : 'none';
        }
        
        prevBtn.style.display = currentStep > 1 ? 'inline-flex' : 'none';
        spacerBtn.style.display = currentStep > 1 ? 'none' : 'block';
        
        if (currentStep === totalSteps) {
            nextBtn.style.display = 'none';
            submitBtn.style.display = 'inline-flex';
            populateReview();
        } else {
            nextBtn.style.display = 'inline-flex';
            submitBtn.style.display = 'none';
        }
        
        renderSteps();
        validateStep();
    }

    prevBtn.addEventListener('click', () => { if (currentStep > 1) { currentStep--; updateView(); } });
    nextBtn.addEventListener('click', () => { if (currentStep < totalSteps) { currentStep++; updateView(); } });

    // Step 1: Customer
    function onCustomerChange() {
        const opt = customerSelect.options[customerSelect.selectedIndex];
        if (opt && opt.value) {
            customerData = {
                name: opt.dataset.name,
                income: parseFloat(opt.dataset.income) || 0,
                debt: parseFloat(opt.dataset.debt) || 0,
                group: opt.dataset.group,
                center: opt.dataset.center,
                aadhaar: opt.dataset.aadhaar,
                pan: opt.dataset.pan
            };
            document.getElementById('previewName').innerText = customerData.name;
            document.getElementById('previewCenter').innerText = customerData.center;
            document.getElementById('previewGroup').innerText = customerData.group;
            document.getElementById('previewAadhaar').innerText = customerData.aadhaar;
            document.getElementById('previewIncome').innerText = '₹' + customerData.income.toLocaleString('en-IN');
            document.getElementById('previewDebt').innerText = '₹' + customerData.debt.toLocaleString('en-IN');
            
            document.getElementById('customerPreview').style.display = 'block';
            document.getElementById('incomeWarning').style.display = customerData.income > 300000 ? 'block' : 'none';
            
            nextBtn.disabled = false;
        } else {
            document.getElementById('customerPreview').style.display = 'none';
            nextBtn.disabled = true;
        }
        calculateFoir();
    }
    customerSelect.addEventListener('change', onCustomerChange);

    // Step 2: Calculator
    const inputs = ['loanAmount', 'loanRate', 'loanTenure', 'loanFrequency', 'loanPurpose'].map(id => document.getElementById(id));
    
    function calculateFoir() {
        const amt = parseFloat(inputs[0].value) || 0;
        const rate = parseFloat(inputs[1].value) || 0;
        const tenure = parseFloat(inputs[2].value) || 0;
        const freq = inputs[3].value;
        
        let emi = 0;
        if (amt && rate && tenure) {
            const r = freq === 'weekly' ? (rate / 100) / 52 : (rate / 100) / 12;
            if (r <= 0) emi = amt / tenure;
            else {
                const f = Math.pow(1 + r, tenure);
                emi = (amt * r * f) / (f - 1);
            }
        }
        
        const mIncome = customerData.income / 12;
        const mEmiEquiv = freq === 'weekly' ? emi * 4.33 : emi;
        const totalObligation = customerData.debt + mEmiEquiv;
        
        let foirPct = 0;
        if (mIncome > 0) foirPct = (totalObligation / mIncome) * 100;
        
        document.getElementById('calcEmi').innerText = '₹' + emi.toLocaleString('en-IN', {maximumFractionDigits: 0});
        document.getElementById('calcIncome').innerText = '₹' + mIncome.toLocaleString('en-IN', {maximumFractionDigits: 0});
        document.getElementById('calcObligation').innerText = '₹' + totalObligation.toLocaleString('en-IN', {maximumFractionDigits: 0});
        
        const foirBar = document.getElementById('foirBar');
        foirBar.style.width = Math.min(foirPct, 100) + '%';
        document.getElementById('foirPctText').innerText = foirPct.toFixed(1) + '%';
        
        foirBar.className = 'gauge-bar ' + (foirPct <= 40 ? 'bg-emerald' : (foirPct <= 50 ? 'bg-yellow' : 'bg-red'));
        
        const status = document.getElementById('foirStatus');
        if (foirPct <= 50) {
            status.innerHTML = '<span class="text-emerald">✅ FOIR within RBI limits</span>';
            submitBtn.disabled = false;
        } else {
            status.innerHTML = '<span class="text-rose">❌ FOIR exceeds 50% RBI cap — application will be rejected</span>';
            submitBtn.disabled = true;
        }
    }
    inputs.forEach(el => el.addEventListener('input', calculateFoir));

    // Step 3: Documents
    function renderDocs() {
        const list = document.getElementById('documentList');
        list.innerHTML = '';
        docs.forEach((doc, idx) => {
            const row = document.createElement('div');
            row.className = 'doc-row';
            row.innerHTML = `
                <select name="doc_types[${idx}]" class="form-input" onchange="docs[${idx}].type = this.value">
                    <option value="">Select document type</option>
                    <option value="aadhaar_card" ${doc.type === 'aadhaar_card'?'selected':''}>Aadhaar Card</option>
                    <option value="pan_card" ${doc.type === 'pan_card'?'selected':''}>PAN Card</option>
                    <option value="voter_id" ${doc.type === 'voter_id'?'selected':''}>Voter ID</option>
                    <option value="bank_passbook" ${doc.type === 'bank_passbook'?'selected':''}>Bank Passbook</option>
                    <option value="income_declaration" ${doc.type === 'income_declaration'?'selected':''}>Income Declaration</option>
                </select>
                <input type="text" name="doc_numbers[${idx}]" class="form-input" value="${doc.number}" placeholder="Document number" onchange="docs[${idx}].number = this.value">
                <input type="file" name="doc_images[${idx}]" class="form-input" accept="image/*">
                ${docs.length > 1 ? `<button type="button" class="btn-icon text-rose" onclick="removeDoc(${idx})">🗑️</button>` : ''}
            `;
            list.appendChild(row);
        });
    }
    
    window.docs = docs;
    window.removeDoc = function(idx) {
        docs.splice(idx, 1);
        renderDocs();
    };
    
    document.getElementById('addDocBtn').addEventListener('click', () => {
        docs.push({type: '', number: ''});
        renderDocs();
    });

    // Step 4: Review
    function populateReview() {
        document.getElementById('revName').innerText = customerData.name;
        document.getElementById('revCenter').innerText = customerData.center + ' / ' + customerData.group;
        
        const amt = parseFloat(inputs[0].value) || 0;
        document.getElementById('revLoan').innerText = '₹' + amt.toLocaleString('en-IN') + ' @ ' + inputs[1].value + '% for ' + inputs[2].value + ' ' + (inputs[3].value === 'weekly' ? 'weeks' : 'months');
        document.getElementById('revEmi').innerText = 'EMI: ' + document.getElementById('calcEmi').innerText + ' | FOIR: ' + document.getElementById('foirPctText').innerText;
        document.getElementById('revPurpose').innerText = inputs[4].value || 'Not specified';
        document.getElementById('revDocs').innerText = docs.filter(d => d.type).length + ' document(s) attached';
        
        const isOk = document.getElementById('foirStatus').innerText.includes('✅');
        const warn = document.getElementById('reviewWarning');
        if (isOk) {
            warn.className = 'alert-success mt-4';
            warn.innerHTML = '<p class="font-bold">✅ All RBI checks passed. Ready to submit.</p>';
        } else {
            warn.className = 'alert-danger mt-4';
            warn.innerHTML = '<p class="font-bold">❌ FOIR exceeds 50% RBI cap. Application will fail RBI validation.</p>';
        }
    }

    // Init
    renderSteps();
    updateView();
    if (customerSelect.value) onCustomerChange();
    renderDocs();
    
    // Form submit
    document.getElementById('loanForm').addEventListener('submit', (e) => {
        submitBtn.innerText = 'Submitting...';
        submitBtn.disabled = true;
    });
});
</script>
@endpush
@endsection
